# Generated by Django 6.0.2 on 2026-06-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('tax', 'Tax consultation'), ('bookkeeping', 'Bookkeeping setup'), ('payroll', 'Payroll review'), ('business_finance', 'Business finance consultation'), ('personal_finance', 'Personal finance consultation')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('business_name', models.CharField(blank=True, max_length=120)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('freelancer', 'Freelancer'), ('small_business', 'Small business'), ('llc_corp', 'LLC / Corporation'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
