# Generated by Django 6.0.2 on 2026-06-22 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_appointment_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(15, 0), '3:00 PM'), (datetime.time(16, 0), '4:00 PM')]),
        ),
    ]
