# Generated by Django 5.2.13 on 2026-06-26 20:41

import datetime
from django.db import migrations, models


def seed_default_availability(apps, schema_editor):
    AvailabilityRule = apps.get_model('bookings', 'AvailabilityRule')

    for weekday in range(5):
        AvailabilityRule.objects.get_or_create(
            weekday=weekday,
            start_time=datetime.time(9, 0),
            end_time=datetime.time(17, 0),
            defaults={
                'slot_duration_minutes': 60,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_appointment_public_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RunPython(seed_default_availability, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time']},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('appointment_date', 'appointment_time'), name='unique_appointment_slot'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrule',
            constraint=models.UniqueConstraint(fields=('weekday', 'start_time', 'end_time'), name='unique_availability_rule'),
        ),
    ]
